[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_if = 'has("nvim")'
hook_add = 'source $XDG_VIM_HOME/plugins/denite.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = 'source $XDG_VIM_HOME/plugins/vim-easymotion.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = 'source $XDG_VIM_HOME/plugins/incsearch.vim'

[[plugins]]
repo = 'haya14busa/incsearch-easymotion.vim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'
hook_add = 'source $XDG_VIM_HOME/plugins/vim-multiple-cursors.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'osyo-manga/vim-over'
hook_add = 'source $XDG_VIM_HOME/plugins/vim-over.vim'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'source $XDG_VIM_HOME/plugins/caw.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = 'source $XDG_VIM_HOME/plugins/rainbow.vim'
